// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {

  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbtM6hTqnRG4khh4dr6pyLZ18UBd4v1lE',
    appId: '1:851552489525:web:581939236c691bce90e17c',
    messagingSenderId: '851552489525',
    projectId: 'phoenix-247205',
    authDomain: 'phoenix-247205.firebaseapp.com',
    databaseURL: 'https://phoenix-247205.firebaseio.com',
    storageBucket: 'phoenix-247205.appspot.com',
    measurementId: 'G-MFTT3HE454',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoR7ZQGpl2rWKIcVMlGI2Re-U0pLqK2hs',
    appId: '1:851552489525:android:892902948806c5f790e17c',
    messagingSenderId: '851552489525',
    projectId: 'phoenix-247205',
    databaseURL: 'https://phoenix-247205.firebaseio.com',
    storageBucket: 'phoenix-247205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl05T_pF0fF4nsZSkeVBXDmrxxic1-KWY',
    appId: '1:851552489525:ios:343561cadcf86ab590e17c',
    messagingSenderId: '851552489525',
    projectId: 'phoenix-247205',
    databaseURL: 'https://phoenix-247205.firebaseio.com',
    storageBucket: 'phoenix-247205.appspot.com',
    androidClientId: '851552489525-2dd42b2eohtu1msnjip4gujmcoa8o4k0.apps.googleusercontent.com',
    iosClientId: '851552489525-kll4n7r5q1uvi7io1h5fpr1g6usm5f05.apps.googleusercontent.com',
    iosBundleId: 'com.arcandia.beescarrier',
  );
}
